### ISSUE TITLE
Input Parameter For Plotting Functions

### ISSUE THREAD

**Issue by cuthchow** [UBC-MDS/Group28-CovidTracker#7]
Would it be more suitable to have the plotting functions take data frames as their arguments as opposed to a file path to a csv? I'm planning for the get_covid_data() function to return a data frame, and having the plotting functions read in a data frame would avoid any issues which arise from reading and parsing other .csv files.

**Comment by jessie14** [comment]
I agree, that makes more sense than reading in a csv file. I'll change the documentation for the plot_geographical function.

**Comment by Davidwang11** [comment]
calculate_stat_summary() function also needs to read the data frame.

**Comment by Davidwang11** [comment]
I found it's difficult for me to summarize the information without knowing the actual columns I will read from the input dataframe.
